#!/bin/bash -e

case $1 in
  remove|upgrade)
      INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
      if [ "systemd" == "${INITSYS}" ]; then
         systemctl stop haltonika || true
         systemctl disable haltonika || true
         rm /lib/systemd/system/haltonika.service || true
         systemctl daemon-reload
      fi
      ;;
esac

exit 0
